# Update list of stocks

In [1]:
import pandas as pd
from pathlib import Path
import configuration as cfg

In [3]:
source_file = cfg.BASE_DIR / "my_data/list_of_stocks.csv"

# Stock list

In [4]:
df = pd.read_csv(source_file)

In [5]:
df.head()

    symbol            name          isin   gsymbol
0   ADS.DE          adidas  DE000A1EWWW0   ADS:ETR
1   6857.T       advantest  JP3122400009  6857:TYO
2  AGFB.BR            agfa  BE0003755692  AGFB:EBR
3   AIR.PA          airbus  NL0000235190   AIR:EPA
4   AFP.XD  air_france_klm  FR001400J770    AF:EPA

# New format

In [15]:
df_new = df.copy()

In [16]:
df_new["ysymbol"] = df_new["symbol"]

In [22]:
df_new["exchange"] = df_new.apply(lambda x: [], axis=1)
df_new["wkn"] = ""
df_new["notes"] = ""

df_new = df_new[["symbol","name","isin","wkn","ysymbol","gsymbol","exchange","notes"]].copy()

In [23]:
df_new.head()

    symbol            name          isin wkn  ysymbol   gsymbol exchange notes
0   ADS.DE          adidas  DE000A1EWWW0       ADS.DE   ADS:ETR       []
1   6857.T       advantest  JP3122400009       6857.T  6857:TYO       []
2  AGFB.BR            agfa  BE0003755692      AGFB.BR  AGFB:EBR       []
3   AIR.PA          airbus  NL0000235190       AIR.PA   AIR:EPA       []
4   AFP.XD  air_france_klm  FR001400J770       AFP.XD    AF:EPA       []

# Exporting

In [24]:
df_new.to_csv(source_file)