# Update list of stocks

In [20]:
import pandas as pd
from pathlib import Path
import configuration as cfg
import csv

In [7]:
source_file = cfg.BASE_DIR / "my_data/list_of_stocks_temp.csv"
output_file = cfg.BASE_DIR / "my_data/list_of_stocks.csv"

In [14]:
# All these columns are string type
NEEDED_COLUMNS = ["name", "isin", "wkn", "ysymbol", "gsymbol", "notes"]

# Stock list

In [22]:
df = pd.read_csv(source_file)

In [23]:
df.head()

,Unnamed: 0,symbol,name,isin,wkn,ysymbol,gsymbol,exchange,notes
0,0,ADS.DE,adidas,DE000A1EWWW0,NaN,ADS.DE,ADS:ETR,[],NaN
1,1,6857.T,advantest,JP3122400009,NaN,6857.T,6857:TYO,[],NaN
2,2,AGFB.BR,agfa,BE0003755692,NaN,AGFB.BR,AGFB:EBR,[],NaN
3,3,AIR.PA,airbus,NL0000235190,NaN,AIR.PA,AIR:EPA,[],NaN
4,4,AFP.XD,air_france_klm,FR001400J770,NaN,AFP.XD,AF:EPA,[],NaN

# Data cleaning

In [24]:
df["notes"] = ""

In [25]:
df.dtypes

Unnamed: 0     int64
symbol        object
name          object
isin          object
wkn           object
ysymbol       object
gsymbol       object
exchange      object
notes         object
dtype: object

In [27]:
df = df.sort_values(by=["name"])
df = df.reset_index()

# New format

In [15]:
df_new = df.copy()

In [16]:
df_new["ysymbol"] = df_new["symbol"]

In [22]:
df_new["exchange"] = df_new.apply(lambda x: [], axis=1)
df_new["wkn"] = ""
df_new["notes"] = ""

df_new = df_new[["symbol","name","isin","wkn","ysymbol","gsymbol","exchange","notes"]].copy()

In [23]:
df_new.head()

    symbol            name          isin wkn  ysymbol   gsymbol exchange notes
0   ADS.DE          adidas  DE000A1EWWW0       ADS.DE   ADS:ETR       []
1   6857.T       advantest  JP3122400009       6857.T  6857:TYO       []
2  AGFB.BR            agfa  BE0003755692      AGFB.BR  AGFB:EBR       []
3   AIR.PA          airbus  NL0000235190       AIR.PA   AIR:EPA       []
4   AFP.XD  air_france_klm  FR001400J770       AFP.XD    AF:EPA       []

# Exporting

In [28]:
df[NEEDED_COLUMNS].to_csv(output_file, quoting=csv.QUOTE_NONNUMERIC, quotechar='"')